#accept connections from any IP (internal docker network)
bind 0.0.0.0

port 6379

#limit the maximum memory usage of Redis
maxmemory 20mb
maxmemory-policy allkeys-lru

#disable saving to disk to improve performance
save ""